### ISSUE TITLE
Now part of elementary OS :)

### ISSUE THREAD

**Issue by aral** [tom95/gala-alternate-alt-tab#12]
Hey Tom,

Just wanted to give you a heads up that [Catts](https://github.com/small-tech/catts) (and thus gala-alt-tab-plus and thus gala-alternate-alt-tab) is now part of elementary OS:

https://blog.elementary.io/elementary-os-6-odin-updates-november-2021/

I already thanked Mark but I also wanted to thank you for originating the project and making this possible.

:two_hearts:

**Comment by tom95** [comment]
Hey @aral, very cool stuff, thank you for the work on this! I'm gonna go ahead and archive this repo then. I also added a notice on the top of the README :)
